// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class SetPerformanceFeeEvent {
  static encode(message: SetPerformanceFeeEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.accountKey);

    writer.uint32(16);
    writer.uint64(message.fee);
  }

  static decode(reader: Reader, length: i32): SetPerformanceFeeEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SetPerformanceFeeEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountKey = reader.string();
          break;

        case 2:
          message.fee = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountKey: string;
  fee: u64;

  constructor(accountKey: string = "", fee: u64 = 0) {
    this.accountKey = accountKey;
    this.fee = fee;
  }
}
