// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class StrategyWithdrawEvent {
  static encode(message: StrategyWithdrawEvent, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.accountKey);

    writer.uint32(16);
    writer.uint64(message.amount);

    writer.uint32(24);
    writer.uint64(message.totalAssets);
  }

  static decode(reader: Reader, length: i32): StrategyWithdrawEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StrategyWithdrawEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountKey = reader.bytes();
          break;

        case 2:
          message.amount = reader.uint64();
          break;

        case 3:
          message.totalAssets = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountKey: Uint8Array;
  amount: u64;
  totalAssets: u64;

  constructor(
    accountKey: Uint8Array = new Uint8Array(0),
    amount: u64 = 0,
    totalAssets: u64 = 0
  ) {
    this.accountKey = accountKey;
    this.amount = amount;
    this.totalAssets = totalAssets;
  }
}
