// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class StrategyInitEvent {
  static encode(message: StrategyInitEvent, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.accountKey);

    writer.uint32(18);
    writer.string(message.strategyType);

    writer.uint32(26);
    writer.bytes(message.vault);

    writer.uint32(34);
    writer.bytes(message.underlyingMint);

    writer.uint32(42);
    writer.bytes(message.underlyingTokenAcc);

    writer.uint32(48);
    writer.uint32(message.underlyingDecimals);

    writer.uint32(56);
    writer.uint64(message.totalIdle);

    writer.uint32(64);
    writer.uint64(message.totalFunds);

    writer.uint32(72);
    writer.uint64(message.depositLimit);

    writer.uint32(80);
    writer.uint64(message.depositPeriodEnds);

    writer.uint32(88);
    writer.uint64(message.lockPeriodEnds);
  }

  static decode(reader: Reader, length: i32): StrategyInitEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StrategyInitEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountKey = reader.bytes();
          break;

        case 2:
          message.strategyType = reader.string();
          break;

        case 3:
          message.vault = reader.bytes();
          break;

        case 4:
          message.underlyingMint = reader.bytes();
          break;

        case 5:
          message.underlyingTokenAcc = reader.bytes();
          break;

        case 6:
          message.underlyingDecimals = reader.uint32();
          break;

        case 7:
          message.totalIdle = reader.uint64();
          break;

        case 8:
          message.totalFunds = reader.uint64();
          break;

        case 9:
          message.depositLimit = reader.uint64();
          break;

        case 10:
          message.depositPeriodEnds = reader.uint64();
          break;

        case 11:
          message.lockPeriodEnds = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountKey: Uint8Array;
  strategyType: string;
  vault: Uint8Array;
  underlyingMint: Uint8Array;
  underlyingTokenAcc: Uint8Array;
  underlyingDecimals: u32;
  totalIdle: u64;
  totalFunds: u64;
  depositLimit: u64;
  depositPeriodEnds: u64;
  lockPeriodEnds: u64;

  constructor(
    accountKey: Uint8Array = new Uint8Array(0),
    strategyType: string = "",
    vault: Uint8Array = new Uint8Array(0),
    underlyingMint: Uint8Array = new Uint8Array(0),
    underlyingTokenAcc: Uint8Array = new Uint8Array(0),
    underlyingDecimals: u32 = 0,
    totalIdle: u64 = 0,
    totalFunds: u64 = 0,
    depositLimit: u64 = 0,
    depositPeriodEnds: u64 = 0,
    lockPeriodEnds: u64 = 0
  ) {
    this.accountKey = accountKey;
    this.strategyType = strategyType;
    this.vault = vault;
    this.underlyingMint = underlyingMint;
    this.underlyingTokenAcc = underlyingTokenAcc;
    this.underlyingDecimals = underlyingDecimals;
    this.totalIdle = totalIdle;
    this.totalFunds = totalFunds;
    this.depositLimit = depositLimit;
    this.depositPeriodEnds = depositPeriodEnds;
    this.lockPeriodEnds = lockPeriodEnds;
  }
}
