// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class VaultDepositEvent {
  static encode(message: VaultDepositEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.vaultIndex);

    writer.uint32(16);
    writer.uint64(message.totalDebt);

    writer.uint32(24);
    writer.uint64(message.totalIdle);

    writer.uint32(32);
    writer.uint64(message.totalShare);

    writer.uint32(40);
    writer.uint64(message.amount);

    writer.uint32(48);
    writer.uint64(message.share);

    writer.uint32(58);
    writer.string(message.tokenAccount);

    writer.uint32(66);
    writer.string(message.shareAccount);

    writer.uint32(74);
    writer.string(message.authority);
  }

  static decode(reader: Reader, length: i32): VaultDepositEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VaultDepositEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.vaultIndex = reader.string();
          break;

        case 2:
          message.totalDebt = reader.uint64();
          break;

        case 3:
          message.totalIdle = reader.uint64();
          break;

        case 4:
          message.totalShare = reader.uint64();
          break;

        case 5:
          message.amount = reader.uint64();
          break;

        case 6:
          message.share = reader.uint64();
          break;

        case 7:
          message.tokenAccount = reader.string();
          break;

        case 8:
          message.shareAccount = reader.string();
          break;

        case 9:
          message.authority = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  vaultIndex: string;
  totalDebt: u64;
  totalIdle: u64;
  totalShare: u64;
  amount: u64;
  share: u64;
  tokenAccount: string;
  shareAccount: string;
  authority: string;

  constructor(
    vaultIndex: string = "",
    totalDebt: u64 = 0,
    totalIdle: u64 = 0,
    totalShare: u64 = 0,
    amount: u64 = 0,
    share: u64 = 0,
    tokenAccount: string = "",
    shareAccount: string = "",
    authority: string = ""
  ) {
    this.vaultIndex = vaultIndex;
    this.totalDebt = totalDebt;
    this.totalIdle = totalIdle;
    this.totalShare = totalShare;
    this.amount = amount;
    this.share = share;
    this.tokenAccount = tokenAccount;
    this.shareAccount = shareAccount;
    this.authority = authority;
  }
}
