// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class VaultDepositEvent {
  static encode(message: VaultDepositEvent, writer: Writer): void {
    writer.uint32(10);
    writer.bytes(message.vaultIndex);

    writer.uint32(16);
    writer.uint64(message.amount);

    writer.uint32(24);
    writer.uint64(message.share);
  }

  static decode(reader: Reader, length: i32): VaultDepositEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VaultDepositEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.vaultIndex = reader.bytes();
          break;

        case 2:
          message.amount = reader.uint64();
          break;

        case 3:
          message.share = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  vaultIndex: Uint8Array;
  amount: u64;
  share: u64;

  constructor(
    vaultIndex: Uint8Array = new Uint8Array(0),
    amount: u64 = 0,
    share: u64 = 0
  ) {
    this.vaultIndex = vaultIndex;
    this.amount = amount;
    this.share = share;
  }
}
