// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0

import { Writer, Reader } from "as-proto/assembly";

export class VaultUpdateDepositLimitEvent {
  static encode(message: VaultUpdateDepositLimitEvent, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.vaultIndex);

    writer.uint32(16);
    writer.uint64(message.newLimit);
  }

  static decode(reader: Reader, length: i32): VaultUpdateDepositLimitEvent {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VaultUpdateDepositLimitEvent();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.vaultIndex = reader.string();
          break;

        case 2:
          message.newLimit = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  vaultIndex: string;
  newLimit: u64;

  constructor(vaultIndex: string = "", newLimit: u64 = 0) {
    this.vaultIndex = vaultIndex;
    this.newLimit = newLimit;
  }
}
